import mongoose from "mongoose";
import { BSC_NURSING_YEARLY_TOTAL } from "../constants/feeStructures.js";

const uploadedDocumentSchema = new mongoose.Schema(
  {
    label: { type: String, trim: true, default: "" },
    url: { type: String, trim: true, default: "" },
    filename: { type: String, trim: true, default: "" },
    originalName: { type: String, trim: true, default: "" },
  },
  { _id: false }
);

const chargeSchema = new mongoose.Schema(
  {
    chargeId: { type: String, trim: true, required: true },
    title: { type: String, trim: true, required: true },
    category: { type: String, trim: true, default: "Miscellaneous" },
    scope: { type: String, trim: true, default: "Additional" },
    amount: { type: Number, required: true, min: 0 },
    dueDate: { type: String, trim: true, default: "" },
    status: { type: String, trim: true, default: "Pending" },
    createdAtLabel: { type: String, trim: true, default: "" },
    note: { type: String, trim: true, default: "" },
  },
  { _id: false }
);

const discountSchema = new mongoose.Schema(
  {
    discountId: { type: String, trim: true, required: true },
    title: { type: String, trim: true, required: true },
    scope: { type: String, trim: true, default: "Student" },
    mode: { type: String, trim: true, default: "Flat" },
    value: { type: Number, default: 0, min: 0 },
    amount: { type: Number, default: 0, min: 0 },
    reason: { type: String, trim: true, default: "" },
    appliedAt: { type: String, trim: true, default: "" },
  },
  { _id: false }
);

const fineRuleSchema = new mongoose.Schema(
  {
    ruleId: { type: String, trim: true, required: true },
    title: { type: String, trim: true, required: true },
    mode: { type: String, trim: true, default: "Flat" },
    value: { type: Number, default: 0, min: 0 },
    graceDays: { type: Number, default: 0, min: 0 },
    active: { type: Boolean, default: true },
  },
  { _id: false }
);

const refundSchema = new mongoose.Schema(
  {
    refundNumber: { type: String, trim: true, required: true },
    amount: { type: Number, required: true, min: 0 },
    reason: { type: String, trim: true, default: "" },
    reference: { type: String, trim: true, default: "" },
    refundDate: { type: String, trim: true, required: true },
    status: { type: String, trim: true, default: "Processed" },
    processedBy: { type: String, trim: true, default: "Admin" },
  },
  { _id: false }
);

const ledgerEntrySchema = new mongoose.Schema(
  {
    entryId: { type: String, trim: true, required: true },
    entryType: { type: String, trim: true, required: true },
    category: { type: String, trim: true, default: "General" },
    title: { type: String, trim: true, required: true },
    amount: { type: Number, required: true, min: 0 },
    direction: { type: String, trim: true, required: true },
    balanceAfter: { type: Number, default: 0, min: 0 },
    entryDate: { type: String, trim: true, required: true },
    reference: { type: String, trim: true, default: "" },
    note: { type: String, trim: true, default: "" },
    status: { type: String, trim: true, default: "Posted" },
  },
  { _id: false }
);

const paymentHistorySchema = new mongoose.Schema(
  {
    receiptNumber: { type: String, trim: true, required: true },
    amount: { type: Number, required: true, min: 0 },
    method: { type: String, trim: true, default: "QR Payment" },
    provider: { type: String, trim: true, default: "Manual" },
    transactionId: { type: String, trim: true, required: true },
    gatewayOrderId: { type: String, trim: true, default: "" },
    gatewayPaymentId: { type: String, trim: true, default: "" },
    gatewaySignature: { type: String, trim: true, default: "" },
    paymentDate: { type: String, trim: true, required: true },
    status: { type: String, trim: true, default: "Confirmed" },
    confirmedBy: { type: String, trim: true, default: "Admin" },
    note: { type: String, trim: true, default: "" },
  },
  { _id: false }
);

const studentSchema = new mongoose.Schema({
  studentName: { type: String, trim: true, required: true },
  registrationNo: { type: String, trim: true, required: true, unique: true },
  admissionNumber: { type: String, trim: true },
  applicationId: { type: String, trim: true },
  year: { type: String, trim: true, required: true },
  admissionYear: { type: String, trim: true, default: "" },
  course: { type: String, trim: true, required: true },
  institution: { type: String, trim: true, default: "" },
  admissionBatch: { type: String, trim: true, default: "" },
  currentStudyYear: { type: Number, default: 1, min: 1, max: 4 },
  feeStructureKey: { type: String, trim: true, default: "" },
  activeFeeStructure: { type: Boolean, default: true },
  feeRevisionHistory: { type: [mongoose.Schema.Types.Mixed], default: [] },
  mScSpecialization: { type: String, trim: true, default: "" },
  highestQualification: { type: String, trim: true, default: "" },
  fullName: String,
  dob: String,
  age: String,
  phone: String,
  whatsappNumber: String,
  email: String,
  admissionDate: String,
  gender: String,
  bloodGroup: String,
  aadhaarNumber: String,
  nationality: String,
  religion: String,
  maritalStatus: String,
  address: String,
  casteCategory: { type: String, trim: true, default: "" },
  fatherName: { type: String, trim: true, default: "" },
  motherName: { type: String, trim: true, default: "" },
  guardianName: { type: String, trim: true, default: "" },
  parentOccupation: { type: String, trim: true, default: "" },
  annualIncome: { type: String, trim: true, default: "" },
  fatherPhone: { type: String, trim: true, default: "" },
  parentEmail: { type: String, trim: true, default: "" },
  parentAadhaarNumber: { type: String, trim: true, default: "" },
  permanentHouseNumber: { type: String, trim: true, default: "" },
  permanentVillage: { type: String, trim: true, default: "" },
  permanentCity: { type: String, trim: true, default: "" },
  permanentDistrict: { type: String, trim: true, default: "" },
  permanentState: { type: String, trim: true, default: "" },
  permanentPinCode: { type: String, trim: true, default: "" },
  presentSameAsPermanent: { type: Boolean, default: false },
  presentHouseNumber: { type: String, trim: true, default: "" },
  presentVillage: { type: String, trim: true, default: "" },
  presentCity: { type: String, trim: true, default: "" },
  presentDistrict: { type: String, trim: true, default: "" },
  presentState: { type: String, trim: true, default: "" },
  presentPinCode: { type: String, trim: true, default: "" },
  tenthSchoolName: { type: String, trim: true, default: "" },
  tenthBoard: { type: String, trim: true, default: "" },
  tenthRollNumber: { type: String, trim: true, default: "" },
  tenthRegistrationNumber: { type: String, trim: true, default: "" },
  tenthPassingYear: { type: String, trim: true, default: "" },
  tenthTotalMarks: { type: String, trim: true, default: "" },
  tenthObtainedMarks: { type: String, trim: true, default: "" },
  tenthPercentage: { type: String, trim: true, default: "" },
  twelfthCollegeName: { type: String, trim: true, default: "" },
  twelfthBoard: { type: String, trim: true, default: "" },
  twelfthRollNumber: { type: String, trim: true, default: "" },
  twelfthRegistrationNumber: { type: String, trim: true, default: "" },
  twelfthPassingYear: { type: String, trim: true, default: "" },
  twelfthStream: { type: String, trim: true, default: "" },
  twelfthPhysicsMarks: { type: String, trim: true, default: "" },
  twelfthChemistryMarks: { type: String, trim: true, default: "" },
  twelfthBiologyMarks: { type: String, trim: true, default: "" },
  twelfthEnglishMarks: { type: String, trim: true, default: "" },
  twelfthHistoryMarks: { type: String, trim: true, default: "" },
  twelfthPoliticalScienceMarks: { type: String, trim: true, default: "" },
  twelfthGeographyMarks: { type: String, trim: true, default: "" },
  twelfthAccountancyMarks: { type: String, trim: true, default: "" },
  twelfthBusinessStudiesMarks: { type: String, trim: true, default: "" },
  twelfthEconomicsMarks: { type: String, trim: true, default: "" },
  twelfthTotalMarks: { type: String, trim: true, default: "" },
  twelfthObtainedMarks: { type: String, trim: true, default: "" },
  twelfthPercentage: { type: String, trim: true, default: "" },
  basicBscNursingCollegeName: { type: String, trim: true, default: "" },
  basicBscNursingUniversity: { type: String, trim: true, default: "" },
  basicBscNursingRollNumber: { type: String, trim: true, default: "" },
  basicBscNursingRegistrationNumber: { type: String, trim: true, default: "" },
  basicBscNursingPassingYear: { type: String, trim: true, default: "" },
  basicBscNursingTotalMarks: { type: String, trim: true, default: "" },
  basicBscNursingObtainedMarks: { type: String, trim: true, default: "" },
  basicBscNursingPercentage: { type: String, trim: true, default: "" },
  postBasicBscNursingCollegeName: { type: String, trim: true, default: "" },
  postBasicBscNursingUniversity: { type: String, trim: true, default: "" },
  postBasicBscNursingRollNumber: { type: String, trim: true, default: "" },
  postBasicBscNursingRegistrationNumber: { type: String, trim: true, default: "" },
  postBasicBscNursingPassingYear: { type: String, trim: true, default: "" },
  postBasicBscNursingTotalMarks: { type: String, trim: true, default: "" },
  postBasicBscNursingObtainedMarks: { type: String, trim: true, default: "" },
  postBasicBscNursingPercentage: { type: String, trim: true, default: "" },
  gnmCollegeName: { type: String, trim: true, default: "" },
  gnmBoard: { type: String, trim: true, default: "" },
  gnmRollNumber: { type: String, trim: true, default: "" },
  gnmRegistrationNumber: { type: String, trim: true, default: "" },
  gnmPassingYear: { type: String, trim: true, default: "" },
  gnmTotalMarks: { type: String, trim: true, default: "" },
  gnmObtainedMarks: { type: String, trim: true, default: "" },
  gnmPercentage: { type: String, trim: true, default: "" },
  casteCertificateUrl: { type: String, trim: true, default: "" },
  casteCertificateFilename: { type: String, trim: true, default: "" },
  supportingDocuments: { type: [uploadedDocumentSchema], default: [] },
  department: { type: String, trim: true, default: "" },
  photoUrl: String,
  photoFilename: String,
  status: { type: String, trim: true, default: "Pending" },
  syncStatus: { type: String, trim: true, default: "Pending Sync" },
  syncNotes: { type: [String], default: [] },
  source: { type: String, trim: true, default: "Website Form" },
  feePlan: { type: String, trim: true, default: "Yearly" },
  totalFee: { type: Number, default: BSC_NURSING_YEARLY_TOTAL, min: 0 },
  baseFee: { type: Number, default: BSC_NURSING_YEARLY_TOTAL, min: 0 },
  totalDiscount: { type: Number, default: 0, min: 0 },
  totalFine: { type: Number, default: 0, min: 0 },
  totalExtraCharges: { type: Number, default: 0, min: 0 },
  outstandingAmount: { type: Number, default: 0, min: 0 },
  lastPaymentDate: { type: String, trim: true, default: "" },
  nextDueDate: { type: String, trim: true, default: "" },
  outstandingStatus: { type: String, trim: true, default: "Pending" },
  paidAmount: { type: Number, default: 0, min: 0 },
  pendingAmount: { type: Number, default: BSC_NURSING_YEARLY_TOTAL, min: 0 },
  scholarshipAmount: { type: Number, default: 0, min: 0 },
  scholarshipStatus: { type: String, trim: true, default: "Not Applied" },
  feeStructure: { type: [chargeSchema], default: [] },
  extraCharges: { type: [chargeSchema], default: [] },
  examFees: { type: [chargeSchema], default: [] },
  discounts: { type: [discountSchema], default: [] },
  fineRules: { type: [fineRuleSchema], default: [] },
  paymentHistory: { type: [paymentHistorySchema], default: [] },
  refunds: { type: [refundSchema], default: [] },
  ledgerEntries: { type: [ledgerEntrySchema], default: [] },
}, { timestamps: true });

export default mongoose.model("Student", studentSchema);
